### ISSUE TITLE
Sharing Violation in Postbuild script

### ISSUE THREAD

**Issue by markman623** [K2NE/K2NEServiceBroker#21]
The XCopy command will result in a 'Sharing Violation' if the dll is already in use. K2 blackpearl service needs to be stopped in postbuilld script to prevent this.  This issue maybe resolved in issue #1 if another deployment script is used.

**Comment by markman623** [comment]
Fixed in my pull request.  Just added, net stop and start to post build script.

**Comment by cyclops1982** [comment]
Hi, 

That net stop/start will fail if you run K2 in console mode. I often do this when developing as it also easily shuts down (click console, hit esc).

I've still not seen any post-build steps that actually handle this all correctly...
